### ISSUE TITLE
tobii 4c linux support and SDK access

### ISSUE THREAD

**Issue by almostnobody** [tobiipro/prosdk-addons-c#2]
Sorry to bother you, i just saw tobii 4c available to purchase, and I am wondering if it is possible to make it work on linux?
In some places on the internet tobii company says i will need to buy some special upgrade pro key for their research license. But it's unclear if it's available for purchase nowdays.

**Comment by jonashogstrom** [comment]
4C is not supported on Linux. Tobii has previously offered a "Product Upgrade Key" for 4C to make it possible to use with the Tobii Pro SDK for analytical use, but we do not offer this any more. We recommend using either Tobii Pro Nano or Tobii Pro Fusion. These trackers are licensed for analytical use already from start and we just released support for Tobii Pro Fusion on Linux. 

If your use case is for interactive use, you can find our offerings for the consumer products like 4C and Tobii Eyetracker 5 on https://developer.tobii.com/ (but there is still no support for 4C on linux as far as I know)
